name: Unit Tests

on:
  push:
    branches: [ "main", "18-coverage-report-not-generated-properly" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install ".[torch]"
          pip install camb
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          python3 tests/run.py
          cat coverage.xml
        shell: bash

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/coverage.xml
          # fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
